<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Logo.ico</ApplicationIcon>
    <ReferencePath>C:\Program Files (x86)\SAP BusinessObjects\Crystal Reports for .NET Framework 4.0\Common\SAP BusinessObjects Enterprise XI 4.0\win64_x64\dotnet\</ReferencePath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Report\ChartReport.rdlc" />
    <None Remove="Report\ResultsReport.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Report\ResultsReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Report\ChartReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf.NetCore3" Version="0.9.8" />
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.14" />
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.19" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.19" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.3" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="XAct.Core.PCL" Version="0.0.5014" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WindowsFormsIntegration">
      <HintPath>C:\Program Files\Reference Assemblies\Microsoft\Framework\v3.0\WindowsFormsIntegration.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="dsResult.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsResult.xsd</DependentUpon>
    </Compile>
    <Compile Update="Views\HomeView_V2.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ChartReportView .xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{c0c07587-41a7-46c8-8fbd-3f9c8ebe2ddc}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CrystalReport1.rpt">
      <Generator>CrystalDecisions.VSDesigner.CodeGen.ReportCodeGenerator</Generator>
    </None>
    <None Update="dsResult.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsResult.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
